def on_button_pressed_b():
    music.set_tempo(212)
    music.play_tone(659, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(784, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    for index in range(2):
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(494, music.beat(BeatFraction.WHOLE))
        music.play_tone(466, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(880, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(494, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
    for index2 in range(2):
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(740, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(622, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(740, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(622, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(740, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(622, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(622, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.DOUBLE))
input.on_button_pressed(Button.B, on_button_pressed_b)
